//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanDuLich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoanDuLich()
        {
            this.BangDangKies = new HashSet<BangDangKy>();
            this.LichTrinhs = new HashSet<LichTrinh>();
            this.PhanCongs = new HashSet<PhanCong>();
        }
    
        public int MaDoanDuLich { get; set; }
        public Nullable<int> MaThoiGianTour { get; set; }
        public string TenDoanDuLich { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public Nullable<int> SoLuongNhanVien { get; set; }
        public Nullable<double> TongTienAnUong { get; set; }
        public Nullable<double> TongTienPhuongTien { get; set; }
        public Nullable<double> TongTienKhachSan { get; set; }
        public Nullable<double> TongTienPhatSinh { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangDangKy> BangDangKies { get; set; }
        public virtual ThoiGianTour ThoiGianTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh> LichTrinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
    }
}
