//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTour
    {
        public int Id { get; set; }
        public Nullable<int> MaTour { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
