//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinh
    {
        public int Id { get; set; }
        public Nullable<int> MaDoanDuLich { get; set; }
        public Nullable<int> Ngay { get; set; }
        public string Buoi { get; set; }
        public Nullable<int> MaChiTietDiaDiem { get; set; }
        public Nullable<int> MaChiPhiKhachSan { get; set; }
        public Nullable<int> MaChiPhiAnUong { get; set; }
        public Nullable<int> MaChiPhiPhuongTien { get; set; }
        public Nullable<int> MaChiPhiPhatSinh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChiPhiAnUong ChiPhiAnUong { get; set; }
        public virtual ChiPhiKhachSan ChiPhiKhachSan { get; set; }
        public virtual ChiPhiPhatSinh ChiPhiPhatSinh { get; set; }
        public virtual ChiPhiPhuongTien ChiPhiPhuongTien { get; set; }
        public virtual ChiTietDiaDiem ChiTietDiaDiem { get; set; }
        public virtual DoanDuLich DoanDuLich { get; set; }
    }
}
