//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int Id { get; set; }
        public Nullable<int> MaDoanDuLich { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> MaNhiemVu { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhiemVu NhiemVu { get; set; }
    }
}
