//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.GiaTours = new HashSet<GiaTour>();
            this.ThoiGianTours = new HashSet<ThoiGianTour>();
            this.TourDiemThamQuans = new HashSet<TourDiemThamQuan>();
        }
    
        public int MaTour { get; set; }
        public Nullable<int> MaLoaiHinh { get; set; }
        public string TenTour { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> SoDem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaTour> GiaTours { get; set; }
        public virtual LoaiHinhDuLich LoaiHinhDuLich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiGianTour> ThoiGianTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourDiemThamQuan> TourDiemThamQuans { get; set; }
    }
}
